# Server
server.port=8080

# API Configuration
api.prefix=/api/v1

# PostgreSQL DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/#databaseName
spring.datasource.username=#username
spring.datasource.password=#password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.default-schema=public
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Logging
logging.level.org.flywaydb=DEBUG

# Swagger / OpenAPI
openapi.title=User Management API
openapi.description=RESTful API documentation for User Management application
openapi.version=v1.0.0

# Servers
openapi.servers[0].url=http://localhost:8080
openapi.servers[0].description=Local Dev
